### ISSUE TITLE
"OWPMLApi\OWPMLUtils.h" 파일, OWPML::COwpmlUtils::ProcessingTextElement(CT*) 함수 누락

### ISSUE THREAD

**Issue by cosine0** [hancom-io/hwpx-owpml-model#2]
이 라이브러리에 "OWPMLApi\OWPMLUtils.h" 파일이 없어서 [hancom-io/dvc](https://github.com/hancom-io/dvc)가 컴파일이 안 됩니다.
이 파일과 관련있는지는 모르겠지만 `OWPML::COwpmlUtils::ProcessingTextElement(CT*)` 함수의 선언도 누락되어 있습니다.
해당 코드 추가 혹은 hancom-io/dvc 해당 부분 수정 부탁드립니다.

**Comment by hnc-jjeong** [comment]
안녕하세요. 해당 컴파일 오류 부분은 dvc쪽에서 수정해서 반영했다고 합니다. 

감사합니다.
